export const PageTitle = 'H.L Toolkits - 图片提取文字';

export const PageSubTitle = `在这个富有文艺气息的网络平台上，释放您内心的创造力！我们是您探索艺术与文字交织之美的理想场所。让我们一同解读图像中隐藏的信息，感受文字的魔力，并探索创意的无限可能性！欢迎来到我们的平台，开启一场奇妙的视觉之旅！`;

export const PageDescription = `在线图片提取文字网站，用于解析您的上传的图片，自动获取图片中的文字内容。`;

export const PageKeywords = [
  'extract image text',
  '图片提取文字',
  'toolkit',
  'toolkits',
  '前端开发',
  '前端开发工具',
  '前端开发工具集合',
  '在线工具',
  'toolbox',
  'frontend',
  '卡鲁秋',
  'Hank',
  'HankLiu',
];

export const Languages = {
  AFR: 'afr',
  AMH: 'amh',
  ARA: 'ara',
  ASM: 'asm',
  AZE: 'aze',
  AZE_CYRL: 'aze_cyrl',
  BEL: 'bel',
  BEN: 'ben',
  BOD: 'bod',
  BOS: 'bos',
  BUL: 'bul',
  CAT: 'cat',
  CEB: 'ceb',
  CES: 'ces',
  CHI_SIM: 'chi_sim',
  CHI_TRA: 'chi_tra',
  CHR: 'chr',
  CYM: 'cym',
  DAN: 'dan',
  DEU: 'deu',
  DZO: 'dzo',
  ELL: 'ell',
  ENG: 'eng',
  ENM: 'enm',
  EPO: 'epo',
  EST: 'est',
  EUS: 'eus',
  FAS: 'fas',
  FIN: 'fin',
  FRA: 'fra',
  FRK: 'frk',
  FRM: 'frm',
  GLE: 'gle',
  GLG: 'glg',
  GRC: 'grc',
  GUJ: 'guj',
  HAT: 'hat',
  HEB: 'heb',
  HIN: 'hin',
  HRV: 'hrv',
  HUN: 'hun',
  IKU: 'iku',
  IND: 'ind',
  ISL: 'isl',
  ITA: 'ita',
  ITA_OLD: 'ita_old',
  JAV: 'jav',
  JPN: 'jpn',
  KAN: 'kan',
  KAT: 'kat',
  KAT_OLD: 'kat_old',
  KAZ: 'kaz',
  KHM: 'khm',
  KIR: 'kir',
  KOR: 'kor',
  KUR: 'kur',
  LAO: 'lao',
  LAT: 'lat',
  LAV: 'lav',
  LIT: 'lit',
  MAL: 'mal',
  MAR: 'mar',
  MKD: 'mkd',
  MLT: 'mlt',
  MSA: 'msa',
  MYA: 'mya',
  NEP: 'nep',
  NLD: 'nld',
  NOR: 'nor',
  ORI: 'ori',
  PAN: 'pan',
  POL: 'pol',
  POR: 'por',
  PUS: 'pus',
  RON: 'ron',
  RUS: 'rus',
  SAN: 'san',
  SIN: 'sin',
  SLK: 'slk',
  SLV: 'slv',
  SPA: 'spa',
  SPA_OLD: 'spa_old',
  SQI: 'sqi',
  SRP: 'srp',
  SRP_LATN: 'srp_latn',
  SWA: 'swa',
  SWE: 'swe',
  SYR: 'syr',
  TAM: 'tam',
  TEL: 'tel',
  TGK: 'tgk',
  TGL: 'tgl',
  THA: 'tha',
  TIR: 'tir',
  TUR: 'tur',
  UIG: 'uig',
  UKR: 'ukr',
  URD: 'urd',
  UZB: 'uzb',
  UZB_CYRL: 'uzb_cyrl',
  VIE: 'vie',
  YID: 'yid',
};

export const LanguageNames = {
  afr: '南非荷兰语',
  amh: '阿姆哈拉语',
  ara: '阿拉伯语',
  asm: '阿萨姆语',
  aze: '阿塞拜疆语',
  aze_cyrl: '阿塞拜疆语 - 西里尔文',
  bel: '白俄罗斯语',
  ben: '孟加拉语',
  bod: '藏语',
  bos: '波斯尼亚语',
  bul: '保加利亚语',
  cat: '加泰罗尼亚语；瓦伦西亚语',
  ceb: '宿务语',
  ces: '捷克语',
  chi_sim: '中文 - 简体',
  chi_tra: '中文 - 繁体',
  chr: '切诺基语',
  cym: '威尔士语',
  dan: '丹麦语',
  deu: '德语',
  dzo: '宗喀语',
  ell: '希腊语，现代（1453-）',
  eng: '英语',
  enm: '英语，中古（1100-1500）',
  epo: '世界语',
  est: '爱沙尼亚语',
  eus: '巴斯克语',
  fas: '波斯语',
  fin: '芬兰语',
  fra: '法语',
  frk: '德国法克图尔语',
  frm: '法语，中古（约1400-1600）',
  gle: '爱尔兰语',
  glg: '加利西亚语',
  grc: '古希腊语，古代（-1453）',
  guj: '古吉拉特语',
  hat: '海地克里奥尔语；海地克里奥尔语',
  heb: '希伯来语',
  hin: '印地语',
  hrv: '克罗地亚语',
  hun: '匈牙利语',
  iku: '因纽特语',
  ind: '印度尼西亚语',
  isl: '冰岛语',
  ita: '意大利语',
  ita_old: '意大利语 - 古代',
  jav: '爪哇语',
  jpn: '日语',
  kan: '卡纳达语',
  kat: '格鲁吉亚语',
  kat_old: '格鲁吉亚语 - 古代',
  kaz: '哈萨克语',
  khm: '高棉语',
  kir: '吉尔吉斯语；柯尔克孜语',
  kor: '朝鲜语',
  kur: '库尔德语',
  lao: '老挝语',
  lat: '拉丁语',
  lav: '拉脱维亚语',
  lit: '立陶宛语',
  mal: '马拉雅拉姆语',
  mar: '马拉地语',
  mkd: '马其顿语',
  mlt: '马耳他语',
  msa: '马来语',
  mya: '缅甸语',
  nep: '尼泊尔语',
  nld: '荷兰语；佛兰芒语',
  nor: '挪威语',
  ori: '奥里亚语',
  pan: '旁遮普语；旁遮普语',
  pol: '波兰语',
  por: '葡萄牙语',
  pus: '普什图语；普什图语',
  ron: '罗马尼亚语；摩尔多瓦语；摩尔多瓦语',
  rus: '俄语',
  san: '梵文',
  sin: '僧伽罗语；僧伽罗语',
  slk: '斯洛伐克语',
  slv: '斯洛文尼亚语',
  spa: '西班牙语；卡斯蒂利亚语',
  sqi: '阿尔巴尼亚语',
  srp: '塞尔维亚语',
  srp_latn: '塞尔维亚语 - 拉丁文',
  swa: '斯瓦希里语',
  swe: '瑞典语',
  syr: '叙利亚语',
  tam: '泰米尔语',
  tel: '泰卢固语',
  tgk: '塔吉克语',
  tgl: '菲律宾语',
  tha: '泰语',
  tir: '提格里尼亚语',
  tur: '土耳其语',
  uig: '维吾尔语；维吾尔语',
  ukr: '乌克兰语',
  urd: '乌尔都语',
  uzb: '乌兹别',
};
